# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'Sonar Execution'
  displayName: 'Sonar Exe'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar-Cloud'
    scannerMode: 'CLI'
    configMode: 'file'
- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
